version: "2"
services:
  web:
    build: .
    env_file:
      - web-variables.env
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
