version: "2"
services:
  web:
    build: .
    env_file:
      - web-variables.env
    environment:
      - NODE_ENV=production
      - PORT=8080
      - MONGODB_URI=mongodb://mongo:27017/workast
    ports:
      - "8080:8080"
